resourceLimits:
  HSB_STUDENT:
    mem_limit: "77"
    cpu_shares: 77
    blk_weight: 77
  HSB_MEMBER:
    mem_limit: "2G"
    cpu_shares: 20
    blk_weight: 0
  HSB_PROF:
    mem_limit: "1G"
    cpu_shares: 20
    blk_weight: 0
