x-hsb-username: 'czoeller'
version: '2.2'
services:
  web:
    image: "nginx:latest"
    container_name: "nginx"
    ports:
      - "8080:8080"
    labels:
      - "hsb.username=czoeller"
    mem_limit: 50M
    cpu_shares: 5
    blkio_config:
      weight: 300